# Generated by Django 5.1.3 on 2024-12-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/placeholder.png', null=True, upload_to='product_images/'),
        ),
    ]
